name: Java Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean package

    - name: Publish JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: factorial-calculator
        path: target/factorial-calculator-1.0-SNAPSHOT.jar
