name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Docker Buildx
        run: |
          # Set up Docker CLI
          echo '{"experimental": "enabled"}' > /home/runner/.docker/config.json
          echo '{"experimental": "enabled"}' > $HOME/.docker/cli-plugins/config.json
          echo '{"experimental": "enabled"}' > $HOME/.docker/config.json
          sudo service docker restart

          # Install Docker Buildx
          git clone https://github.com/docker/buildx
          cd buildx
          sudo make install

      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker build -t my-java-app:latest -f Dockerfile .
          docker images

      - name: Archive Docker image
        if: success()
        run: |
          mkdir -p artifacts
          docker save -o artifacts/my-java-app.tar my-java-app:latest

      - name: Upload Docker image as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: my-java-app
          path: artifacts/my-java-app.tar
