name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build Docker image
      run: docker buildx build --file Dockerfile --output type=image,registry-image:$GITHUB_REPOSITORY:latest .

    - name: Upload Docker image as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ./.buildx-cache
