name: Java Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust to your desired Java version

    - name: Compile Java Program
      run: javac SumCalculator.java

    - name: Run Java Program
      run: java SumCalculator
