name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'  # Update to the desired Java version

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-application
        path: target/my-application.jar
